/**:
  ros__parameters:
    use_sim_time: true
    pointcloud_topic: "/livox/lidar"
    imu_topic: "/livox/imu"
    frames/odom: "odom"
    frames/baselink: "base_link"
    frames/lidar: "lidar"
    frames/imu: "imu"
    map/waitUntilMove: false
    map/dense/filtered: true
    map/sparse/leafSize: 0.05
    odom/gravity: 9.80665
    odom/computeTimeOffset: true
    odom/imu/approximateGravity: true
    odom/imu/calibration/gyro: true
    odom/imu/calibration/accel: true
    odom/imu/calibration/time: 5.0
    odom/imu/bufferSize: 5000

    # Réduction vitale pour ne pas aveugler le capteur face aux parois collées
    odom/preprocessing/cropBoxFilter/size: 0.15
    # Résolution extrême pour capter les moindres anfractuosités
    odom/preprocessing/voxelFilter/res: 0.05

    # Enregistrement permanent dicté par la faible vitesse de reptation
    odom/keyframe/threshD: 0.2
    # Tolérance angulaire très élevée pour ignorer les à-coups de la tête
    odom/keyframe/threshR: 5.0

    # Confinement absolu du solveur à la géométrie de contact
    odom/gicp/minNumPoints: 50
    odom/gicp/kCorrespondences: 20
    odom/gicp/maxCorrespondenceDistance: 0.5
    odom/gicp/maxIterations: 64
    odom/gicp/transformationEpsilon: 0.001
    odom/gicp/rotationEpsilon: 0.0001
    odom/gicp/initLambdaFactor: 1e-9

    # Mémoire minimale pour éviter un verrouillage tubulaire fatal
    odom/submap/keyframe/knn: 20
    odom/submap/keyframe/kcv: 20
    odom/submap/keyframe/kcc: 20

    # Chute de l'autorité du laser sur l'axe longitudinal
    odom/geo/Kp: 0.5
    odom/geo/Kv: 1.0
    # Suprématie totale de la centrale inertielle pour préserver l'attitude
    odom/geo/Kq: 5.0
    odom/geo/Kab: 1.0
    odom/geo/Kgb: 1.0
    odom/geo/abias_max: 4.0
    odom/geo/gbias_max: 0.5